#!/bin/bash
# MIMICWizard Application Setup Script
# This script installs R dependencies and configures the application

set -e

echo "=== MIMICWizard Application Setup ==="
echo ""

# Check if R is installed
echo "Checking R installation..."
if ! command -v R &> /dev/null; then
    echo "ERROR: R is not installed"
    echo "Please install R from: https://www.r-project.org/"
    exit 1
fi

R_VERSION=$(R --version | head -n 1)
echo "✓ Found: $R_VERSION"
echo ""

# Install R packages
echo "Installing required R packages..."
echo "This may take 10-20 minutes depending on your system..."
echo ""

R --vanilla << 'EOF'
# Set CRAN mirror
options(repos = c(CRAN = "https://cloud.r-project.org"))

# List of required packages
packages <- c(
  # Shiny and UI
  "shiny",
  "shiny.semantic",
  "shinyjs",
  "waiter",
  
  # Database
  "DBI",
  "RPostgres",
  "dbplyr",
  
  # Data manipulation
  "dplyr",
  "tidyr",
  "purrr",
  "lubridate",
  
  # Visualization
  "plotly",
  "ggplot2",
  "DT",
  "gt",
  
  # Utilities
  "jsonlite",
  "future",
  "tryCatchLog"
)

cat("Checking and installing packages...\n")
for (pkg in packages) {
  if (!require(pkg, character.only = TRUE, quietly = TRUE)) {
    cat(paste0("Installing ", pkg, "...\n"))
    install.packages(pkg, dependencies = TRUE)
  } else {
    cat(paste0("✓ ", pkg, " already installed\n"))
  }
}

cat("\n=== Package Installation Complete ===\n")
EOF

echo ""
echo "✓ R packages installed"
echo ""

# Configure global.R
echo "Configuring application settings..."
echo ""
echo "Please provide your database connection details:"
echo "(Press Enter to use default values shown in brackets)"
echo ""

read -p "Database name [mimiciv]: " DB_NAME
DB_NAME=${DB_NAME:-mimiciv}

read -p "Database host [localhost]: " DB_HOST
DB_HOST=${DB_HOST:-localhost}

read -p "Database port [5432]: " DB_PORT
DB_PORT=${DB_PORT:-5432}

read -p "Database user [postgres]: " DB_USER
DB_USER=${DB_USER:-postgres}

read -sp "Database password (leave empty if none): " DB_PASSWORD
echo ""

echo ""
echo "Application mode:"
echo "  1) Direct connection (skip intro screen)"
echo "  2) Interactive mode (show intro screen)"
read -p "Select mode [1]: " APP_MODE
APP_MODE=${APP_MODE:-1}

# Update global.R with settings
cd "$(dirname "$0")/.."

if [ "$APP_MODE" = "1" ]; then
    INTERACTIVE="FALSE"
else
    INTERACTIVE="TRUE"
fi

cat > global.R << EOF
# MIMICWizard Global Configuration
# Auto-generated by setup script

CONFIG <- list(
  INTERACTIVE = $INTERACTIVE,
  APPLICATION_MODE = "HOSTED",
  CACHE_DIR = "",
  DATABASE_MODE = "HOSTED",
  IS_ED_LOADED = FALSE,
  IS_NOTE_LOADED = FALSE,
  
  # Hosted database configuration
  HOSTED_DBNAME = "$DB_NAME",
  HOSTED_HOST = "$DB_HOST",
  HOSTED_PORT = $DB_PORT,
  HOSTED_USER = "$DB_USER",
  HOSTED_PASSWORD = "$DB_PASSWORD",
  
  # Demo database configuration (not used in hosted mode)
  DEMO_DBNAME = "postgres",
  DEMO_HOST = "localhost",
  DEMO_PORT = 5432,
  DEMO_USER = "postgres",
  DEMO_PASSWORD = ""
)
EOF

echo ""
echo "✓ Application configured"
echo ""

# Test database connection
echo "Testing database connection..."
R --vanilla << EOF
source("global.R")
library(DBI)
library(RPostgres)

tryCatch({
  conn <- dbConnect(
    RPostgres::Postgres(),
    dbname = CONFIG\$HOSTED_DBNAME,
    host = CONFIG\$HOSTED_HOST,
    port = CONFIG\$HOSTED_PORT,
    user = CONFIG\$HOSTED_USER,
    password = CONFIG\$HOSTED_PASSWORD
  )
  
  # Check for required schemas
  schemas <- dbGetQuery(conn, "SELECT schema_name FROM information_schema.schemata")
  
  required_schemas <- c("mimiciv_hosp", "mimiciv_icu")
  missing_schemas <- setdiff(required_schemas, schemas\$schema_name)
  
  if (length(missing_schemas) > 0) {
    cat("WARNING: Missing required schemas:", paste(missing_schemas, collapse=", "), "\n")
    cat("Please ensure MIMIC-IV data is properly loaded.\n")
  } else {
    cat("✓ Database connection successful\n")
    cat("✓ Required schemas found\n")
  }
  
  dbDisconnect(conn)
}, error = function(e) {
  cat("ERROR: Database connection failed\n")
  cat("Error message:", conditionMessage(e), "\n")
  quit(status = 1)
})
EOF

echo ""
echo "=== Application Setup Complete ==="
echo ""
echo "To start MIMICWizard:"
echo "  cd $(dirname "$0")/.."
echo "  R -e \"shiny::runApp(port = 3838, launch.browser = FALSE)\""
echo ""
echo "Then open your browser to: http://localhost:3838"
echo ""
